<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeviceBattery.Domain\DeviceBattery.Domain.csproj" />
    <ProjectReference Include="..\DeviceBattery.Application\DeviceBattery.Application.csproj" />
  </ItemGroup>
</Project>
