<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeviceBattery.Application\DeviceBattery.Application.csproj" />
    <ProjectReference Include="..\DeviceBattery.Domain\DeviceBattery.Domain.csproj" />
  </ItemGroup>
</Project>
